name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          21,
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build